"""initial schema

Revision ID: bf7fc02c8256
Revises: 
Create Date: 2026-08-10 17:24:41.883545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf7fc02c8256'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('units',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('origin', sa.String(length=32), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('contact', sa.String(length=255), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('copy_requests',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('origin', sa.String(length=32), nullable=False),
    sa.Column('unit_id', sa.String(length=64), nullable=False),
    sa.Column('unit_name', sa.String(length=255), nullable=False),
    sa.Column('requester', sa.String(length=255), nullable=False),
    sa.Column('contact', sa.String(length=255), nullable=False),
    sa.Column('document_description', sa.String(length=500), nullable=False),
    sa.Column('pages', sa.Integer(), nullable=False),
    sa.Column('copies', sa.Integer(), nullable=False),
    sa.Column('duplex', sa.Boolean(), nullable=False),
    sa.Column('printed_faces', sa.Integer(), nullable=False),
    sa.Column('consumed_sheets', sa.Integer(), nullable=False),
    sa.Column('paper', sa.String(length=16), nullable=False),
    sa.Column('color_mode', sa.String(length=16), nullable=False),
    sa.Column('priority', sa.String(length=32), nullable=False),
    sa.Column('desired_deadline', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('production_owner', sa.String(length=255), nullable=False),
    sa.Column('requested_at', sa.String(length=10), nullable=False),
    sa.Column('produced_at', sa.String(length=10), nullable=False),
    sa.Column('delivered_at', sa.String(length=10), nullable=False),
    sa.Column('picked_up_by', sa.String(length=255), nullable=False),
    sa.Column('notes', sa.String(length=2000), nullable=False),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_copy_requests_code'), 'copy_requests', ['code'], unique=True)
    op.create_table('status_history_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('date', sa.String(length=10), nullable=False),
    sa.Column('by', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['copy_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('status_history_entries')
    op.drop_index(op.f('ix_copy_requests_code'), table_name='copy_requests')
    op.drop_table('copy_requests')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('units')
    # ### end Alembic commands ###
