"""add signature to copy_requests

Revision ID: c6ab4b463b02
Revises: 4245329c67ae
Create Date: 2026-08-19 18:29:46.628598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6ab4b463b02'
down_revision: Union[str, Sequence[str], None] = '4245329c67ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('copy_requests', sa.Column('signature', sa.Text(), nullable=False, server_default=''))
    op.alter_column('copy_requests', 'signature', server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('copy_requests', 'signature')
    # ### end Alembic commands ###
