"""add role_permissions table

Revision ID: 49103c221504
Revises: 40e91ff86d59
Create Date: 2026-08-11 02:52:20.542915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49103c221504'
down_revision: Union[str, Sequence[str], None] = '40e91ff86d59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    role_permissions = op.create_table('role_permissions',
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('permission', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('role', 'permission')
    )
    # ### end Alembic commands ###

    # Semeia com os valores fixos que existiam antes desta tabela (ver
    # DEFAULT_ROLE_PERMISSIONS em app/core/permissions.py) — daqui em diante
    # a tabela é a fonte de verdade, editável em Perfis de Acesso.
    default_role_permissions = {
        "Admin": [
            "viewDashboard",
            "createRequests",
            "editRequests",
            "updateProduction",
            "manageUnits",
            "manageUsers",
            "manageAudit",
        ],
        "Gerente": ["viewDashboard", "createRequests", "editRequests", "updateProduction", "manageUnits", "manageUsers"],
        "Operador": ["viewDashboard", "createRequests", "editRequests", "updateProduction"],
        "Consulta": ["viewDashboard"],
    }
    op.bulk_insert(
        role_permissions,
        [
            {"role": role, "permission": permission}
            for role, permissions in default_role_permissions.items()
            for permission in permissions
        ],
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('role_permissions')
    # ### end Alembic commands ###
