"""add registration_number to copy_requests

Revision ID: e6bef415cea2
Revises: 49103c221504
Create Date: 2026-08-11 03:50:56.209659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6bef415cea2'
down_revision: Union[str, Sequence[str], None] = '49103c221504'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('copy_requests', sa.Column('registration_number', sa.String(length=64), nullable=False, server_default=''))
    op.alter_column('copy_requests', 'registration_number', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('copy_requests', 'registration_number')
    # ### end Alembic commands ###
