import { apiFetch } from "../../../shared/api/apiClient";
import { DiscoveryNetwork, DiscoveryRun, ManualPrinterDraft, NetworkDraft, Page, Printer, PrinterSupply, SupplyReading } from "../model/types";

const mapNetwork = (row: any): DiscoveryNetwork => ({ id: row.id, name: row.name, cidr: row.cidr, excludedCidrs: row.excluded_cidrs, snmpVersion: row.snmp_version, timeoutMs: row.timeout_ms, retries: row.retries, concurrencyLimit: row.concurrency_limit, active: row.active, credentialConfigured: row.credential_configured, targetCount: row.target_count, isPrivate: row.is_private, createdAt: row.created_at, updatedAt: row.updated_at });
const runStatus = (value: string): DiscoveryRun["status"] => value.toUpperCase() === "PENDING" ? "queued" : value.toLocaleLowerCase() as DiscoveryRun["status"];
const mapRun = (row: any): DiscoveryRun => ({ id: row.id, networkId: row.network_id, status: runStatus(row.status), totalTargets: row.total_targets, scannedTargets: row.scanned_targets, responsiveDevices: row.responsive_devices, printersFound: row.printers_found, newPrinters: row.new_printers, errorCount: row.error_count, requestedByUserId: row.requested_by_user_id, requestedAt: row.requested_at, startedAt: row.started_at, finishedAt: row.finished_at, heartbeatAt: row.heartbeat_at, lastErrorCode: row.last_error_code, lastErrorMessage: row.last_error_message });
const operationalStatus = (value: string): Printer["operationalStatus"] => ({ ONLINE: "online", IDLE: "online", PRINTING: "online", WARMUP: "online", WARNING: "warning", ERROR: "warning", OFFLINE: "offline", NO_COMMUNICATION: "offline", UNKNOWN: "unknown" }[value.toUpperCase()] as Printer["operationalStatus"] ?? "unknown");
const mapPrinter = (row: any): Printer => ({ id: row.id, discoveryNetworkId: row.discovery_network_id, managementAddress: row.management_address, macAddress: row.mac_address, serialNumber: row.serial_number, sysObjectId: row.sys_object_id, sysName: row.sys_name, sysDescription: row.sys_description, manufacturer: row.manufacturer, model: row.model, displayName: row.display_name, unitId: row.unit_id, onboardingStatus: String(row.onboarding_status).toLocaleLowerCase() as Printer["onboardingStatus"], monitoringEnabled: row.monitoring_enabled, operationalStatus: operationalStatus(row.operational_status), normalizedErrors: row.normalized_errors, consecutivePollFailures: row.consecutive_poll_failures, firstSeenAt: row.first_seen_at, lastSeenAt: row.last_seen_at, lastPolledAt: row.last_polled_at, updatedAt: row.updated_at });
const supplyAlert = (value: string): PrinterSupply["alertStatus"] => ({ NORMAL: "ok", WARNING: "warning", CRITICAL: "critical", UNKNOWN: "unknown" }[value.toUpperCase()] as PrinterSupply["alertStatus"] ?? "unknown");
const mapSupply = (row: any): PrinterSupply => ({ id: row.id, printerId: row.printer_id, snmpIndex: row.snmp_index, descriptionRaw: row.description_raw, normalizedType: String(row.normalized_type).toLocaleLowerCase(), color: String(row.color).toLocaleLowerCase(), capacityRaw: row.capacity_raw, levelRaw: row.level_raw, capacityUnitRaw: row.capacity_unit_raw, levelPercent: row.level_percent, alertStatus: supplyAlert(row.alert_status), warningThresholdPercent: row.warning_threshold_percent, criticalThresholdPercent: row.critical_threshold_percent, lastSeenAt: row.last_seen_at });

function networkBody(draft: Partial<NetworkDraft>) {
  return { name: draft.name, cidr: draft.cidr, excluded_cidrs: draft.excludedCidrs, community: draft.community, timeout_ms: draft.timeoutMs, retries: draft.retries, concurrency_limit: draft.concurrencyLimit };
}

export function createPrintFleetRepository() {
  const base = "/api/v1/print-fleet";
  return {
    async getNetworks() { return (await apiFetch<any[]>(`${base}/networks`)).map(mapNetwork); },
    async createNetwork(draft: NetworkDraft) { return mapNetwork(await apiFetch<any>(`${base}/networks`, { method: "POST", body: JSON.stringify(networkBody(draft)) })); },
    async updateNetwork(id: string, draft: Partial<NetworkDraft>) { return mapNetwork(await apiFetch<any>(`${base}/networks/${id}`, { method: "PATCH", body: JSON.stringify(networkBody(draft)) })); },
    async setNetworkActive(id: string, active: boolean) { return mapNetwork(await apiFetch<any>(`${base}/networks/${id}/active`, { method: "PATCH", body: JSON.stringify({ active }) })); },
    async startDiscovery(id: string) { return mapRun(await apiFetch<any>(`${base}/networks/${id}/discoveries`, { method: "POST" })); },
    async getDiscoveries(page = 1, pageSize = 25): Promise<Page<DiscoveryRun>> { const data = await apiFetch<any>(`${base}/discoveries?page=${page}&page_size=${pageSize}`); return { items: data.items.map(mapRun), total: data.total, page: data.page, pageSize: data.page_size }; },
    async getPrinters(filters: { page?: number; pageSize?: number; onboardingStatus?: string; unitId?: string } = {}): Promise<Page<Printer>> { const q = new URLSearchParams({ page: String(filters.page ?? 1), page_size: String(filters.pageSize ?? 100) }); if (filters.onboardingStatus) q.set("onboarding_status", filters.onboardingStatus); if (filters.unitId) q.set("unit_id", filters.unitId); const data = await apiFetch<any>(`${base}/printers?${q}`); return { items: data.items.map(mapPrinter), total: data.total, page: data.page, pageSize: data.page_size }; },
    async createPrinter(draft: ManualPrinterDraft) { const body = { discovery_network_id: draft.discoveryNetworkId, management_address: draft.managementAddress, display_name: draft.displayName, unit_id: draft.unitId, manufacturer: draft.manufacturer || null, model: draft.model || null, serial_number: draft.serialNumber || null, mac_address: draft.macAddress || null }; return mapPrinter(await apiFetch<any>(`${base}/printers`, { method: "POST", body: JSON.stringify(body) })); },
    async confirmPrinter(id: string, displayName: string, unitId: string) { return mapPrinter(await apiFetch<any>(`${base}/printers/${id}/confirm`, { method: "POST", body: JSON.stringify({ display_name: displayName, unit_id: unitId }) })); },
    async setOnboarding(id: string, action: "ignore" | "reopen") { return mapPrinter(await apiFetch<any>(`${base}/printers/${id}/${action}`, { method: "POST" })); },
    async setMonitoring(id: string, enabled: boolean) { return mapPrinter(await apiFetch<any>(`${base}/printers/${id}/monitoring`, { method: "PATCH", body: JSON.stringify({ enabled }) })); },
    async getSupplies(id: string) { return (await apiFetch<any[]>(`${base}/printers/${id}/supplies`)).map(mapSupply); },
    async getReadings(printerId: string, supplyId: string, limit = 100): Promise<SupplyReading[]> { const rows = await apiFetch<any[]>(`${base}/printers/${printerId}/supplies/${supplyId}/readings?limit=${limit}`); return rows.map((row) => ({ id: row.id, printerSupplyId: row.printer_supply_id, capacityRaw: row.capacity_raw, levelRaw: row.level_raw, capacityUnitRaw: row.capacity_unit_raw, levelPercent: row.level_percent, alertStatus: supplyAlert(row.alert_status), recordedAt: row.recorded_at })); },
  };
}
